USE [master]
GO
/****** Object:  Database [Group3_Phase1]    Script Date: 6/15/2023 5:58:15 PM ******/
CREATE DATABASE [Group3_Phase1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Group3_Phase1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Group3_Phase1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Group3_Phase1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Group3_Phase1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Group3_Phase1] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Group3_Phase1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Group3_Phase1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Group3_Phase1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Group3_Phase1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Group3_Phase1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Group3_Phase1] SET ARITHABORT OFF 
GO
ALTER DATABASE [Group3_Phase1] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Group3_Phase1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Group3_Phase1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Group3_Phase1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Group3_Phase1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Group3_Phase1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Group3_Phase1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Group3_Phase1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Group3_Phase1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Group3_Phase1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Group3_Phase1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Group3_Phase1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Group3_Phase1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Group3_Phase1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Group3_Phase1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Group3_Phase1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Group3_Phase1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Group3_Phase1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Group3_Phase1] SET  MULTI_USER 
GO
ALTER DATABASE [Group3_Phase1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Group3_Phase1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Group3_Phase1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Group3_Phase1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Group3_Phase1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Group3_Phase1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Group3_Phase1] SET QUERY_STORE = ON
GO
ALTER DATABASE [Group3_Phase1] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Group3_Phase1]
GO
/****** Object:  Table [dbo].[Property]    Script Date: 6/15/2023 5:58:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Property](
	[PropertyID] [int] NOT NULL,
	[UserID] [int] NULL,
	[Address] [varchar](100) NULL,
	[Neighborhood] [varchar](50) NULL,
	[SquareFeet] [int] NULL,
	[ParkingGarage] [bit] NULL,
	[PublicTransport] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 6/15/2023 5:58:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Phone] [varchar](15) NULL,
	[Email] [varchar](50) NULL,
	[Role] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Workspace]    Script Date: 6/15/2023 5:58:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Workspace](
	[WorkspaceID] [int] NOT NULL,
	[PropertyID] [int] NULL,
	[Type] [varchar](50) NULL,
	[Capacity] [int] NULL,
	[SmokingAllowed] [bit] NULL,
	[AvailabilityDate] [date] NULL,
	[LeaseTerm] [varchar](20) NULL,
	[Price] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[WorkspaceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Property]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Workspace]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[Property] ([PropertyID])
GO
USE [master]
GO
ALTER DATABASE [Group3_Phase1] SET  READ_WRITE 
GO
